name: Push to Quartz Vault

on: push

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Pushes test folder
      uses: datalbry/copy_folder_to_another_repo_action@1.0.0
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_folder: './'
        destination_repo: 'metamageia/The-Metamageia-Vault'
        destination_folder: 'content'
        destination_branch: 'main'
        user_email: 'metamageia@gmail.com'
        user_name: 'metamageia'
        commit_msg: 'Update Quartz Website Content'