name: Push to Dailies Test

on: push

jobs:
  update-dailies-quartz:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Remove .obsidian and .github folders
      run: rm -rf .obsidian .github

    - name: Check file existence
      id: check_files
      uses: andstor/file-existence-action@v3
      with:
        files: "./daily/index.md"

    - name: File exists
      if: steps.check_files.outputs.files_exists == 'true'
      run: echo "index.md check passed!"

    - name: File exists
      if: steps.check_files.outputs.files_exists == 'false'
      run: |
        echo "index.md does not exist! Please provide an index.md file - aborting"
        exit 1

    - name: Pushes obsidan root folder
      uses: datalbry/copy_folder_to_another_repo_action@1.0.0
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_folder: './daily'
        destination_repo: 'metamageia/dailies'
        destination_folder: 'content'
        destination_branch: 'main'
        user_email: 'metamageia@gmail.com'
        user_name: 'metamageia'
        commit_msg: 'Update the dailies Quartz Website Content'
